language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

install:
    pip install --use-mirrors cython

script:
  - python -u setup.py clean
  - python -u setup.py build_ext --inplace
  - PYTHONUNBUFFERED=x make test

matrix:
  allow_failures:
    - python: pypy
